# -*- coding: utf-8 -*-
"""Portfolio_optimize_VQE.ipynb

Automatically generated by Colab.


"""

#!pip install --upgrade qiskit qiskit-finance numpy pandas matplotlib

"""The stock data will be ingested from the TwelveData momentum app into the notebook for use in the Qiskit VQE"""

#Import all the necessary libraries from Qiskit
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from qiskit_finance.data_providers import RandomDataProvider
from qiskit_finance.applications.optimization import PortfolioOptimization
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit.primitives import StatevectorSampler as Sampler
from qiskit.circuit.library import TwoLocal
from qiskit_algorithms import SamplingVQE
from qiskit_algorithms.optimizers import COBYLA

#!pip install streamlit

#Obtain the current prices through a market API such as Twelve Data in this case. See the stock price compilation python script
import pandas as pd
stock_data=pd.read_csv('portfolio_etfs.csv')
stock_data.head()

#Review the assets and their covariance for selecting a sample for the opitmization
selected_assets = ['NVDA', 'OXY', 'TXG', 'CVE','FTNT','TWST']
portfolio_data = stock_data[selected_assets].cov()
print("Stock Covariance Matrix:")
print(portfolio_data)

#Use the quantity of tickers for stocks for setting the total qubits to run with the IBM backend
num_assets =len(selected_assets)
expected_returns = stock_data[selected_assets].mean()

#Select a risk and asset number for the first portfolio optimization
risk_factor = 0.5  # Adjust risk tolerance
budget = 4  # Number of assets to select

# Define Portfolio Optimization
portfolio = PortfolioOptimization(
    expected_returns=expected_returns,
    covariances=portfolio_data.values, # Convert DataFrame to NumPy array
    risk_factor=risk_factor,
    budget=budget
)

# Convert it to the Quadratic Program for the portfolio return 
quadratic_program = portfolio.to_quadratic_program()
print("\nPortfolio Optimization Problem:")
print(quadratic_program)



#Use the Sampling VQE algorithm and first, Define Variational Ansatz (Two-Local circuit)
#Choose only one rep for the 1st run for the time to run but it can be increased to say, reps=3 in the ansatz 
ansatz = TwoLocal(num_assets,  rotation_blocks=["ry", "rz"], entanglement_blocks="cz")
# Define the optimizer to use
optimizer = COBYLA(maxiter=100)
# Using the State Vector Sampler Simular, Initialize the Sampler primitive
sampler = Sampler()

# Set up the the SamplingVQE algorithm
sampling_vqe = SamplingVQE(sampler=sampler, ansatz=ansatz, optimizer=optimizer)

# Solve the Portfolio Optimization Problem using the Minimum Eigen Optimizer
qaoa = MinimumEigenOptimizer(sampling_vqe)
result = qaoa.solve(quadratic_program)

#Refer to the Qiskit documentation to print the results in this format for probabilities those selected
from qiskit.result import QuasiDistribution
from qiskit_algorithms import NumPyMinimumEigensolver, QAOA, SamplingVQE
import numpy as np

def print_result(result):
    selection = result.x
    value = result.fval
    print("Optimal: selection {}, value {:.4f}".format(selection, value))

    eigenstate = result.min_eigen_solver_result.eigenstate
    if isinstance(eigenstate, QuasiDistribution):
        probabilities = eigenstate.binary_probabilities()
    elif isinstance(eigenstate, dict):
        probabilities = {k: np.abs(v) ** 2 for k, v in eigenstate.items()}
    else:
        probabilities = {k: np.abs(v) ** 2 for k, v in eigenstate.to_dict().items()}

    print("\n----------------- Full result ---------------------")
    print("selection\tvalue\t\tprobability")
    print("---------------------------------------------------")
    probabilities = sorted(probabilities.items(), key=lambda x: x[1], reverse=True)

    for k, v in probabilities:
        x = np.array([int(i) for i in list(reversed(k))])
        value = portfolio.to_quadratic_program().objective.evaluate(x)
        print("%10s\t%.4f\t\t%.4f" % (x, value, v))
#In the printed reuslts a lower (more negative) value represents a higher expected return relative to the risk/variance penalty
#Multiply the assets selected by the vector of stock tickers to get the 4 out of 6 selected by the VQE job
print_result(result)

