# -*- coding: utf-8 -*-
"""Portfolio_optimize_VQE.ipynb

Automatically generated by Colab.


"""

#!pip install --upgrade qiskit qiskit-finance numpy pandas matplotlib

"""The stock data will be ingested from the TwelveData momentum app into the notebook for use in the Qiskit VQE"""

#Import all the necessary libraries from Qiskit
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from qiskit_finance.data_providers import RandomDataProvider
from qiskit_finance.applications.optimization import PortfolioOptimization
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit.primitives import StatevectorSampler as Sampler
from qiskit.circuit.library import TwoLocal
from qiskit_algorithms import SamplingVQE
from qiskit_algorithms.optimizers import COBYLA



#!pip install streamlit

#Obtain the current prices through a market API such as Twelve Data in this case. See the stock price compilation python script
import pandas as pd
stock_data=pd.read_csv('portfolio_etfs.csv')
stock_data.head()

#Review the assets and their covariance for selecting a sample for the opitmization
selected_assets = ['NVDA', 'OXY', 'TXG', 'CVE','FTNT','TWST']
portfolio_data = stock_data[selected_assets].cov()
print("Stock Covariance Matrix:")
print(portfolio_data)

expected_returns = stock_data[selected_assets].mean()

#Select a risk and asset number for the first portfolio optimization run
risk_factor = 0.5  # Adjust risk tolerance
budget = 4  # Number of assets to select

# Define Portfolio Optimization
portfolio = PortfolioOptimization(
    expected_returns=expected_returns,
    covariances=portfolio_data.values, # Convert DataFrame to NumPy array
    risk_factor=risk_factor,
    budget=budget
)

# Convert to the Quadratic Program for the portfolio optimization training
quadratic_program = portfolio.to_quadratic_program()
print("\nPortfolio Optimization Problem:")
print(quadratic_program)

#Use the Sampling VQE algorithm and first, Define the Variational Ansatz (Two-Local circuit)
ansatz = TwoLocal(rotation_blocks=["ry", "rz"], entanglement_blocks="cz")

# Define the selected classical optimizer which in this case could be chosen as Adam as well
optimizer = COBYLA(maxiter=100)

# Using the Qiskit State Vector Sampler Simulator for 6 securities, Initialize the Sampler primitive
sampler = Sampler()

# Set up the SamplingVQE algorithm since QAOA is a specialized, structurally constrained subclass of SamplingVQE
sampling_vqe = SamplingVQE(sampler=sampler, ansatz=ansatz, optimizer=optimizer)

# Solve the Portfolio Optimization Problem using the Minimum Eigenvalue  Optimizer
qaoa = MinimumEigenOptimizer(sampling_vqe)
result = qaoa.solve(quadratic_program)

#Results interpretation
optimal_portfolio = portfolio.interpret(result)
optimal_portfolio = np.atleast_1d(optimal_portfolio)  # Ensure 1D array with numpy

# Select indices of chosen assets
selected_assets = np.where(optimal_portfolio == 1)[0]
selected_tickers = [stock_data.columns[i] for i in selected_assets]

# Print selected assets
print(f"\nOptimal Portfolio Allocation: {selected_tickers}")

#Visualize Optimal Portfolio Selection
all_assets = ['NVDA', 'OXY', 'TXG', 'CVE', 'FTNT', 'TWST']

plt.figure(figsize=(8, 5))
colors = ['green' if asset in selected_tickers else 'gray' for asset in all_assets]
plt.bar(all_assets, expected_returns, color=colors)
plt.xlabel("Assets")
plt.ylabel("Expected Returns")
plt.title("Optimal Portfolio Allocation")
plt.show()

